
%open file, create roi, get mean

%[fileToRead1, ~] = uigetfile('*.avi','File Selector');
% Import the file
%  Auto-generated by MATLAB on 05-Aug-2021 17:25:35
%rawData1 = importdata(fileToRead1);
% For some simple files (such as a CSV or JPEG files), IMPORTDATA might
% return a simple array.  If so, generate a structure so that the output
% matches that from the Import Wizard.
%[~,name] = fileparts(fileToRead1);
%newData1.(matlab.lang.makeValidName(name)) = rawData1;
% Create new variables in the base workspace from those fields.
%vars = fieldnames(newData1);
%for i = 1:length(vars)
%    assignin('base', vars{i}, newData1.(vars{i}));
%end

[filename1, ~] = uigetfile('*.avi','File Selector');

test_vid = VideoReader(filename1);
frame = read(test_vid, 10);

imshow(frame);
roi = drawcircle;
disp('draw roi, press key to continue')
pause;

roimask1 = roi.createMask;

roi_mean = zeros(test_vid.NumFrames,1);

for i = 1:test_vid.NumFrames
    active_frame = read(test_vid, i);
    roi_mean(i, 1) = mean(active_frame(roimask1), 'all'); 
end